### ISSUE TITLE
Enemies keep chasing even on map switch

### ISSUE THREAD

**Issue by oribro** [oribro/Spacehack#10]
When the player gets ambushed by the 3 dogfish and then tries to run away to the previous map, the 3 dogfish will be there on different tiles.
I guess this was not intended and monsters shouldn't be transferable between maps, similar to Nethack's behaviour.

In addition, for some reason the sound of dogfish snarl is being accompanied by the water pour over the fire as happened in the first map.

So, these are the two bug fixes we should address:

- [ ]  Restrict npcs to their native map such that they shouldn't be able to move between maps.
- [x]  Seperate between dogfish snarl and the water sound on river ambush.

**Comment by razieli** [comment]
Regarding the second "bug": The sound of the water splash in map "2,0" is on purpose, it's because the 3 dogfish are coming out of the water (don't forget they are half fish).

**Comment by razieli** [comment]
For the first issue I went on a different approach that I think makes more sense. 

I made the NPCs chase the player if he moves to an adjacent map. When the player switches maps they will keep moving in the direction of that map, and eventually when they reach the edge they will move to the player's map.

This feels more natural because an adjacent map in our game is simply area next to you so the NPCs should still be able to see you there.
